[colors.primary]
background = '#fffcf0'
foreground = '#100f0f'

[colors.selection]
text = '#100f0f'
background = '#163b66'

[colors.cursor]
text = '#fffcf0'
cursor = '#205ea6'

[colors.normal]
black   = '#100F0F'
red     = '#9d0432'
green   = '#007c10'
yellow  = '#c7bc00'
blue    = '#1a5eae'
magenta = '#bddbff'
cyan    = '#205EA6'
white   = '#2b2c2e'

[colors.bright]
black   = '#87898d'
red     = '#cd2d5a'
green   = '#14b62a'
yellow  = '#d7cc00'
blue    = '#2b6dc9'
magenta = '#bddbff'
cyan    = '#80a9d7'
white   = '#f0f4f9'
